temps = c(98.5, 99.4, 101.2, 98.1)
mean(temps)
sd(temps)
colleges = read.csv("colleges.csv")
View(colleges)
hist(colleges$num.FT.undergrad)
hist(colleges$num.FT.undergrad, main="Full-time undergrads in US Colleges", xlab="Number of undergrads")
boxplot(colleges$Graduation.rate)
boxplot(colleges$out.of.state.tuition ~ colleges$Region)
plot(colleges$Verbal.SAT, colleges$Math.SAT)
plot(colleges$Verbal.SAT, colleges$Math.SAT, pch=3)
plot(colleges$Verbal.SAT, colleges$Math.SAT, col="red")
colleges$Public.or.Private = as.factor(colleges$Public.or.Private)
plot(colleges$in.state.tuition, colleges$out.of.state.tuition, col=colleges$Public.or.Private)